---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - args:
          - --config-file
          - .github/.yamllint.yaml
        id: yamllint
