---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: miniflux
      version: "4.x.x"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    postgresql:
      enable: true
      persistence:
        enabled: true
        storageClass: local-path
  interval: 1m0s
