---
version: '3'
services:
  app:
    environment:
      - APP_BASE_URL=${HOSTNAME}
      - APP_PORT=22300
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - DB_CLIENT=pg
    restart: unless-stopped
    image: joplin/server:latest
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joplin.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.joplin.entrypoints=websecure"
      - "traefik.http.routers.joplin.tls.certresolver=mytlschallenge"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.joplin.loadbalancer.server.port=22300"
      - "traefik.http.services.joplin.loadbalancer.passhostheader=true"
    networks:
      - joplin
      - traefik
  db:
    restart: unless-stopped
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
    networks:
      - joplin

volumes:
  db:


networks:
  traefik:
    external: true
  joplin:
